In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.empty(2) #Empty 1D Tensor
y = torch.empty(3,4) #Empty 2D Tensor
z = torch.empty(5,1,6) #Empty 3D Tensor

In [ ]:
x

tensor([1.9235e-10, 4.4351e-41])

In [ ]:
y

tensor([[5.3406e-24, 3.3124e-41, 5.3144e-24, 3.3124e-41],
        [7.2708e+31, 5.0778e+31, 3.2608e-12, 1.7728e+28],
        [7.0367e+22, 2.1715e-18, 1.3445e+22, 2.1478e-04]])

In [ ]:
z

tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4013e-45,
          0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4013e-45,
          0.0000e+00]],

        [[9.1845e-41, 1.1551e-40, 4.5919e-41, 8.2957e-43, 1.9185e-20,
          4.4351e-41]]])

In [ ]:
a = torch.ones(1,2) #Fills with 1s
b = torch.zeros(3, dtype = int) #Fills with 0s + typecasts to int {default being float32"}

In [ ]:
c = torch.tensor([3.2,4.8,9.6]) #Creating a tensor array

In [ ]:
d = torch.rand(3,1,4)
d

tensor([[[0.3019, 0.2603, 0.4287, 0.5307]],

        [[0.6807, 0.3968, 0.2689, 0.7360]],

        [[0.1740, 0.8579, 0.0825, 0.0720]]])

In [ ]:
e = torch.rand(2,2)
f = torch.rand(2,2)

g = e+f
h = torch.add(e,f)

print(g) #element-wise addition
print(h) #element-wise addition

tensor([[0.7195, 0.8922],
        [1.2106, 1.6300]])
tensor([[0.7195, 0.8922],
        [1.2106, 1.6300]])


In [ ]:
e.add_(f) #in-place addition


tensor([[0.7195, 0.8922],
        [1.2106, 1.6300]])

In [ ]:
i = e-f
j = torch.sub(e,f)

print(i)
print(j)

tensor([[0.0949, 0.3255],
        [0.7311, 0.9745]])
tensor([[0.0949, 0.3255],
        [0.7311, 0.9745]])


In [ ]:
k = e*f
l = torch.mul(e,f)

print(k)
print(l)

tensor([[0.4493, 0.5057],
        [0.5804, 1.0685]])
tensor([[0.4493, 0.5057],
        [0.5804, 1.0685]])


In [ ]:
g = e.view(4) #resizing tensor array
g

tensor([0.7195, 0.8922, 1.2106, 1.6300])

In [ ]:
m = e.view(-1,4) #-1 denotes not specifying size in one dimension and 4 specifies size in the other dimension
print(m.size())

torch.Size([1, 4])


In [ ]:
m

tensor([[0.7195, 0.8922, 1.2106, 1.6300]])

In [ ]:
a = torch.ones(5)
print(a)
          #Converting from tensor to numpy
b = a.numpy()
print(b) #Note: a & b both point to the same variable location in memory; so any alterations in any one variable
         # will automatically affect the other variable. [if operation is happening in CPU]

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [ ]:
c = np.ones(6)
print(c)
         #Converting from numpy to tensor
d = torch.from_numpy(c)
print(d) #Note: c & d both point to the same variable location in memory; so any alterations in any one variable
         # will automatically affect the other variable. [if operation is happening in CPU]



[1. 1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
if torch.cuda.is_available():

  device = torch.device("cuda")
  x = torch.ones(5, device=device) #Creating a tensor in GPU using CUDA toolkit

  y = torch.ones(5) #Originally creating a tensor in CPU
  y = y.to(device) #Converting from CPU tensor to GPU tensor
  z = x+y          # Adding up tensors in GPU
  z = z.to("cpu")  #Converting the result obtained in GPU tensor to CPU tensor



In [ ]:
d = torch.ones(10, requires_grad=True) #Creates a tensor where optimization may be required later on: so gradients are computed through this option
print(d)